### ISSUE TITLE
Release 5.6 checklist

### ISSUE THREAD

**Issue by thejoshwolfe** [thejoshwolfe/legend-of-swarkland#80]
- [x] restrictions on which species can kick
- [x] become a rhino
- [x] controls tutorial in the first level for moving and attacking
- [x] controls tutorial for waiting in the level when you're a blob
- [x] controls tutorial for restarting the current level
- [x] level select should not animate the cheatcode macros
- [x] level select should not allow rewinding past where you started
- [x] `r` to undo to the start of the current level
- [x] the beat level cheatcode should effectively push `r` first, then use the macro for the current level.
- [x] the unbeat level cheatcode should effectively be `r` unless you're already at the start of the level.
- [x] windows build
- [x] main menu should show the full path to the save file
- [x] tutorial in the main menu for resizing the window
- [x] turn `Action` validation errors from the gui client into `reject` responses instead of assertion failures to workaround the crash when pushing two arrow keys at the same time while playing as a blob.
- [x] moving into a blob should succeed.
- [x] kicking a blob should suck you in.
- [x] rhino turning animation should swap the orientation of the sprite midway through the move instead of at the end.
- [x] main menu cursor should start on level select if you have >0 levels unlocked
- [x] level select cursor should always start at the end of the list
- [x] better final level
- [x] blobs should shrink backward if that would bring them closer to their target
- [x] polymorph trap should fail if it would make multiple non-blob individuals overlap afterward
